### ISSUE TITLE
Update https://github.com/PerseusDL/canonical-pdlpsci

### ISSUE THREAD

**Issue by jacobwegner** [scaife-viewer/scaife-cts-api#6]
https://github.com/PerseusDL/canonical-pdlpsci/releases/tag/0.0.56

- [x] Update `scaife-cts-api`
- [x] Update search index
- [x] Cache purge

**Comment by jacobwegner** [comment]
Hi @ievrigenis,

I'm working with @jtauber to further systematize and automate the update process for https://scaife.perseus.org.

I hope to get Scaife Viewer updated with latest release of https://github.com/PerseusDL/canonical-pdlpsci/ pushed out tonight or tomorrow and will update this issue when complete.

**Comment by jacobwegner** [comment]
Deployed in the [v0.1.2_20190313_001 release](https://github.com/scaife-viewer/scaife-cts-api/releases/tag/v0.1.2_20190313_001)

**Comment by ievrigenis** [comment]
Many thanks, Jacob!


On Mar 13, 2019, at 9:12 AM, Jacob Wegner <notifications@github.com<mailto:notifications@github.com>> wrote:


Deployed in the v0.1.2_20190313_001 release<https://github.com/scaife-viewer/scaife-cts-api/releases/tag/v0.1.2_20190313_001>
